fix: render context chat's the referenced source items
nextcloud/assistant pull request #124
Opened 2024-09-16 10:10 UTC by kyteinsky

2024-09-16 10:11 UTC, kyteinsky commented
Not sure if there is a cleaner way. Should we move the entire output render to context chat's form?

2024-09-16 11:39 UTC, julien-nc requested changes

2024-09-16 11:39 UTC, julien-nc commented on src/components/AssistantTextProcessingForm.vue
> +				</div>
Let's put as few Context-Chat-specific stuff as possible in this file. The label text can go in the `ContextChatOutputSources` component.

Also we can do something similar than for the input form. In this file, the output `TaskTypeFields` component and this new `div` could be moved in a `AssistantFormOutputs` component.

Wdyt?

2024-09-17 08:23 UTC, julien-nc approved these changes

2024-09-17 08:41 UTC, merged