feat: save default target language & set detect_language as origin default
nextcloud/assistant pull request #167
Opened 2024-12-18 15:51 UTC by janepie

This adds a short loading time before task types will be shown in the assistant modal. Ideas how to prevent that very welcome :)

2025-01-07 16:22 UTC, julien-nc requested changes
Recommendation for the delay issue.

2025-01-07 16:22 UTC, julien-nc commented on src/components/AssistantTextProcessingForm.vue
> +					this.getLastTargetLanguage()
It would probably work to call this asynchronously and change the task type (in `this.taskTypes`) once you get the answer.

It would mean keeping the previous code (`taskTypes.forEach` and then `this.taskTypes = taskTypes`) and then doing the `this.getLastTargetLanguage().then(r => // find and change the task type in this.taskTypes)`

This would solve the delay issue as the `taskTypes` data prop would be set as soon as possible. It would not be slowed down by `this.getLastTargetLanguage()`.

2025-01-08 11:09 UTC, julien-nc approved these changes
Added a small fix and switched to using initial state + an OCA.Assistant variable to handle the last target language.

2025-01-08 12:37 UTC, marcelklehr approved these changes

2025-01-08 12:37 UTC, merged