Implement pdf content extraction
nextcloud/assistant pull request #170
Opened 2024-12-20 21:53 UTC by dhx

Currently pdf files can't be used as a text source in the assistant (while they work in context chat).

2024-12-27 08:46 UTC, dhx commented
Hi @julien-nc I see you've added rtf support, so maybe you can take a look if this implementation for pdf looks good to you or if something is missing?

2025-02-03 15:16 UTC, julien-nc requested changes
Looks good!

Can you rebase on the main branch?
There's a conflict with composer.lock. Just get rid of yours, rebase on main, install `smalot/pdfparser` and make a new commit.

2025-03-04 13:53 UTC, closed without merging

2025-03-04 13:54 UTC, julien-nc commented
I made another PR with some adjustments. See #204
Thanks for your PR though!

2025-03-08 21:43 UTC, dhx commented
@julien-nc thanks for taking it over!